[commit.generation]
command = "MAX_THINKING_TOKENS=0 claude -p --no-session-persistence --model=haiku --tools='' --safe-mode --setting-sources='user' --system-prompt=''"

[projects]

[projects."github.com-work/*"]
worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[projects."github.com/*"]
worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[list]
summary=true
