# *****************************************************************************
# .ZSHRC
# *****************************************************************************

# *****************************************************************************
# PACKAGE MANAGERS
# *****************************************************************************

# Homebrew on Linux. On macOS the awesome-lazy-zsh managed block below runs
# `brew shellenv` itself.
[ -x /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# pnpm
case "$(uname -s)" in
  Darwin) export PNPM_HOME="$HOME/Library/pnpm" ;;
  *)      export PNPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm" ;;
esac
# pnpm 11 and older keep the binary in $PNPM_HOME, pnpm 12 and newer in $PNPM_HOME/bin.
for _pnpm_dir in "$PNPM_HOME/bin" "$PNPM_HOME"; do
  case ":$PATH:" in
    *":$_pnpm_dir:"*) ;;
    *) export PATH="$_pnpm_dir:$PATH" ;;
  esac
done
unset _pnpm_dir
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# *****************************************************************************
# TOOLCHAIN PATH ADDITIONS
# *****************************************************************************

# Assorted `export PATH=...` lines dropped in by various CLI/IDE
# installers. Some duplicate each other (kept as installed - see
# notes below - harmless, just redundant).

ZSH_COLORIZE_STYLE="github-dark"

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"

# opencode
export PATH=$HOME/.opencode/bin:$PATH

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
export PATH="$PATH:$HOME/go/bin"
export PATH="$HOME/.local/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:$HOME/.lmstudio/bin"
# End of LM Studio CLI section

# duplicates the $HOME/.local/bin export above
# Added by Antigravity CLI installer
export PATH="$HOME/.local/bin:$PATH"

# Vite+ bin (https://viteplus.dev)
[ -f "$HOME/.vite-plus/env" ] && . "$HOME/.vite-plus/env"

# Added by Antigravity IDE
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"

# Pi
export PATH="$HOME/.vite-plus/js_runtime/node/24.19.0/bin:$PATH"

# duplicates the Antigravity IDE export above
# Added by Antigravity IDE
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"

# *****************************************************************************
# ALIASES
# *****************************************************************************

alias uncommit="git reset --soft HEAD~1"
alias claude2='CLAUDE_CONFIG_DIR=~/.config/claude-code-sub2 claude'

# *****************************************************************************
# RUNTIME VERSION MANAGER (MISE)
# *****************************************************************************

if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
elif [ -x "$HOME/.local/bin/mise" ]; then
  eval "$($HOME/.local/bin/mise activate zsh)"
fi

# *****************************************************************************
# OH-MY-ZSH / AWESOME-LAZY-ZSH
# *****************************************************************************

# Managed by the awesome-lazy-zsh CLI - contents between the
# >>>/<<< markers are regenerated by that tool. Do not hand-edit
# or reorder anything inside; customizations go above it.

# Completions that bootstrap/install.sh generates into ~/.zfunc (pass-cli ships a
# generator, not a file). It must be on fpath before the block below: oh-my-zsh
# runs compinit inside it.
fpath=(~/.zfunc $fpath)

# >>> awesome-lazy-zsh managed block >>>
#      _                                               _                         _____    _
#     / \__      _____  ___  ___  _ __ ___   ___      | |    __ _ _____   _     |__  /___| |__
#    / _ \ \ /\ / / _ \/ __|/ _ \| '_ ` _ \ / _ \_____| |   / _` |_  / | | |_____ / // __| '_ \
#   / ___ \ V  V /  __/\__ \ (_) | | | | | |  __/_____| |__| (_| |/ /| |_| |_____/ /_\__ \ | | |
#  /_/   \_\_/\_/ \___||___/\___/|_| |_| |_|\___|     |_____\__,_/___|\__, |    /____|___/_| |_|
#                                                                      |___/
#
#  https://github.com/AmJaradat01/awesome-lazy-zsh
#  DO NOT EDIT THIS BLOCK - Your customizations should go ABOVE this block
#  Last updated: 2026-08-30T11:32:00.885Z

# Path to your Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Theme
# ZSH_THEME="starship"

# Plugins
plugins=(git git-flow npm nvm docker docker-compose vscode extract dotenv ssh-agent node gitfast z thefuck zsh-autosuggestions zsh-syntax-highlighting)
# Complete selection for profiles (includes aliases/custom plugins)
# awesome-lazy-zsh-plugins=["git","git-flow","npm","nvm","docker","docker-compose","vscode","extract","dotenv","ssh-agent","node","gitfast","z","thefuck","zsh-autosuggestions","zsh-syntax-highlighting","python","golang","rust","java","git-extras","ssh","directories","history-search","flutter"]

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Homebrew PATH for Apple Silicon
export PATH="/opt/homebrew/bin:$PATH"

# Visual Studio Code Path
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Docker Path
export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin/"

# Docker Aliases
alias dps='docker ps'
alias dstop='docker stop $(docker ps -a -q)'
alias drm='docker rm $(docker ps -a -q)'
alias dimages='docker images'
alias dbuild='docker build -t'

# Docker CLI completions
fpath=(~/.docker/completions $fpath)
autoload -Uz compinit
compinit

# NVM Setup
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

# Git Branch Function
git_branch() {
    git branch 2>/dev/null | grep '^*' | colrm 1 2
}

# System Optimizations
# macOS specific settings
export BROWSER="open"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Terminal Integration
source $HOME/.iterm2_shell_integration.zsh

# Local secrets (untracked, outside the dotfiles repo — never commit this file's target)
[ -f "$HOME/.secrets.zsh" ] && source "$HOME/.secrets.zsh"

# Awesome-Lazy-Zsh Custom Aliases
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/extract.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/extract.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/dotenv.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/dotenv.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/node.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/node.zsh"
unalias pi 2>/dev/null  # frees `pi` for pi-coding-agent binary; plugin above aliases it to `pnpm install`
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/python.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/python.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/golang.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/golang.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/rust.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/rust.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/java.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/java.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/git-extras.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/git-extras.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/ssh.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/ssh.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/directories.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/directories.zsh"
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/history.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/aliases/history.zsh"

# Awesome-Lazy-Zsh Alias Manager
[ -f "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/alias-manager.zsh" ] && source "/opt/homebrew/opt/awesome-lazy-zsh/libexec/src/alias-manager.zsh"
# <<< awesome-lazy-zsh managed block <<<

# Overrides for the managed block above. They live outside it so that
# awesome-lazy-zsh regenerating the block can't undo them.
# - nvm's node has to beat the brew node that `brew shellenv` put first on PATH.
[ -n "$NVM_BIN" ] && export PATH="$NVM_BIN:$PATH"
# - the block sets BROWSER=open, which only exists on macOS.
[[ "$OSTYPE" == darwin* ]] || unset BROWSER

# *****************************************************************************
# SHELL INTEGRATION / PROMPT
# *****************************************************************************

# iterm2 integration is also sourced inside the managed block
# above; this guarded re-source is a harmless no-op belt-and-
# braces left over from before that block existed.
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
eval "$(starship init zsh)"
export EDITOR="nvim"

# *****************************************************************************
# SSH AGENT
# *****************************************************************************

# Two agent sockets set back to back; the second export wins, so
# ProtonPass is what's actually active - Secretive's line is dead
# code as written, left as-is (not my call to drop it), just
# relocated next to its sibling so the override is obvious instead
# of one line sitting 90 lines away from the other.
# macOS only. Elsewhere (a VPS) SSH_AUTH_SOCK is left alone, so a forwarded agent
# (ssh -A) keeps working instead of being pointed at a socket that isn't there.
if [[ "$OSTYPE" == darwin* ]]; then
  export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

  #ProtonPass SSH-Agent
  export SSH_AUTH_SOCK=$HOME/.ssh/proton-pass-ssh-agent.sock
fi

# *****************************************************************************
# FZF
# *****************************************************************************

# setup fzf keybindings and completions
eval "$(fzf --zsh)"

# fzf theme
# --- setup fzf theme ---
fg="#CBE0F0"
bg="#000000"
bg_highlight="#143652"
purple="#B388FF"
blue="#06BCE4"
cyan="#2CF9ED"

export FZF_DEFAULT_OPTS="--color=fg:${fg},bg:${bg},hl:${purple},fg+:${fg},bg+:${bg_highlight},hl+:${purple},info:${blue},prompt:${cyan},pointer:${cyan},marker:${cyan},spinner:${cyan},header:${cyan}"


# -- Use fd instead of fzf --

export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

source ~/fzf-git.sh/fzf-git.sh

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

_fzf_comprun(){
  local command=$1
  shift

  case "$command" in
    cd) fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
    ssh) fzf --preview 'dig {}' "$@" ;;
    *) fzf --preview 'bat -n --color=always --line-range :500 {}' "$@" ;;
    esac
}

# *****************************************************************************
# CLI REPLACEMENTS — BAT / EZA / ZOXIDE
# *****************************************************************************

# ----- Bat (better cat) -----

export BAT_THEME=tokyonight_night

# ---- Eza (better ls) -----

alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

alias cd="z"


# *****************************************************************************
# COMPLETIONS (CARAPACE)
# *****************************************************************************

#  carapace
autoload -U compinit && compinit
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)
zstyle ':completion:*:git:*' group-order 'main commands' 'alias commands' 'external commands'
#worktrunk
if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init zsh)"; fi

# Worktree hooks in each repo's .config/wt.toml read these; spelled out here so
# changing one is a single edit. One-off override: WT_AGENTS= wt switch -c x
export WT_TMUX=on                    # tmux session per worktree (off to skip)
export WT_AGENTS="claude opencode"   # agents started in the Agents window ("" for none)
export WT_EDITOR=nvim                # editor in the Editor window
export WT_PROXY=on                   # Caddy route per worktree (off to skip)

# use the defined nodejs version if present in the folder via .nvmrc
chpwd(){
  if [[ -f .nvmrc ]] && (( $+functions[nvm] )); then
    nvm use
  fi
}

# ZSH zsh-syntax-highlighting configuration
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

# Homebrew (macOS, then Linuxbrew) first, then the distro package.
for _zsh_hl in \
  /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
  /home/linuxbrew/.linuxbrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
  /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh; do
  if [ -f "$_zsh_hl" ]; then source "$_zsh_hl"; break; fi
done
unset _zsh_hl

typeset -A ZSH_HIGHLIGHT_PATTERNS
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_MAXLENGTH=512
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=(/mnt/nfs-share)

# Catppuccin Mocha colors (ansi mapping: magenta=Pink, cyan=Teal)
ctp_pink='#f5c2e7' ctp_teal='#94e2d5'
ZSH_HIGHLIGHT_STYLES[alias]="fg=$ctp_pink,bold"
ZSH_HIGHLIGHT_STYLES[path]="fg=$ctp_teal"
ZSH_HIGHLIGHT_STYLES[globbing]='none'

[ -f "$HOME/.atuin/bin/env" ] && . "$HOME/.atuin/bin/env"

command -v atuin >/dev/null 2>&1 && eval "$(atuin init zsh)"
