# *****************************************************************************
# PANES
# *****************************************************************************

# PANE BORDER LOOK AND FEEL
#-------------------------------------------------------
setw -g pane-border-status top
setw -g pane-border-format " #I#{?#{!=:#{window_name},Window},: #W,} "
setw -g pane-active-border-style "bg=terminal,fg=#{@thm_overlay_0}" # transparent background
setw -g pane-border-style "bg=terminal,fg=#{@thm_surface_0}"
setw -g pane-border-lines single

# POPUP LOOK AND FEEL (prefix + s sesh picker)
#-------------------------------------------------------
set -g popup-border-lines rounded
set -g popup-border-style "fg=#{@thm_mauve}"
