palette = 0=#3B544D
palette = 1=#f07178
palette = 2=#C3E88D
palette = 3=#FFCB6B
palette = 4=#6FA0DE
palette = 5=#A68DCD
palette = 6=#74C9DE
palette = 7=#CAE5D5
palette = 8=#3B544D
palette = 9=#f07178
palette = 10=#C3E88D
palette = 11=#FFCB6B
palette = 12=#6FA0DE
palette = 13=#A68DCD
palette = 14=#74C9DE
palette = 15=#ffffff
background = #111816
foreground = #CAE5D5
cursor-color = #FFCC00
cursor-text = #111816
selection-background = #4B7253
selection-foreground = #CAE5D5
