palette = 0=#676E95
palette = 1=#f07178
palette = 2=#C3E88D
palette = 3=#FFCB6B
palette = 4=#82AAFF
palette = 5=#C792EA
palette = 6=#89DDFF
palette = 7=#CED1E3
palette = 8=#676E95
palette = 9=#f07178
palette = 10=#C3E88D
palette = 11=#FFCB6B
palette = 12=#82AAFF
palette = 13=#C792EA
palette = 14=#89DDFF
palette = 15=#ffffff
background = #292D3E
foreground = #CED1E3
cursor-color = #FFCC00
cursor-text = #292D3E
selection-background = #555C82
selection-foreground = #CED1E3
