palette = 0=#545454
palette = 1=#f07178
palette = 2=#C3E88D
palette = 3=#FFCB6B
palette = 4=#82AAFF
palette = 5=#C792EA
palette = 6=#89DDFF
palette = 7=#D9D9D9
palette = 8=#545454
palette = 9=#f07178
palette = 10=#C3E88D
palette = 11=#FFCB6B
palette = 12=#82AAFF
palette = 13=#C792EA
palette = 14=#89DDFF
palette = 15=#ffffff
background = #212121
foreground = #D9D9D9
cursor-color = #FFCC00
cursor-text = #212121
selection-background = #474747
selection-foreground = #D9D9D9
